name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "./src/FileManager.Web"
    - name: Build
      run: dotnet build "./src/FileManager.Web" --configuration Release --no-restore
    - name: Publish application
      run: dotnet publish "./src/FileManager.Web" -c Release -o "./src/FileManager.Web/publish"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: file-manager-release
       path: "./src/FileManager.Web/publish" 
